Move things

diff --git a/.github/workflows/docs-pr.yml b/.github/workflows/docs-pr.yml
--- a/.github/workflows/docs-pr.yml
+++ b/.github/workflows/docs-pr.yml
@@ -1,25 +1,33 @@
-# This is an example of the docs-pr.yml workflow available from the recrwplay org
-name: "Verify PR"
+# This is an example of the docs-build-verify.yml workflow available from the recrwplay org
+name: "Verify docs PR"
 
 on:
   pull_request:
 
 jobs:
 
-  vale:
-    name: Vale
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - uses: errata-ai/vale-action@reviewdog
-        with:
-          files: 'modules/ROOT/pages'
-          reporter: github-pr-check
-        env:
-          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
+  # deploy-comment:
+  #   name: Generate deploy comment text
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check out PR branch
+  #       uses: actions/checkout@v3
+        
 
+  set-deploy-outputs:
+    runs-on: ubuntu-latest
+    # Map a step output to a job output
+    outputs:
+      deploy-id: ${{ github.event.number }}
+      deploy-url: ${{ steps.get-deploy-url.outputs.deploy-url }}
+    steps:
+      - id: get-deploy-url
+        run: |
+          deployurl=${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ github.event.number }}.surge.sh
+          echo "deploy-url=$deployurl" >> $GITHUB_OUTPUT      
        
-  build-verify-deploy:
+  build-verify:
+    name: Verify Antora log
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -29,14 +37,51 @@ jobs:
 
       # build and verify
 
-      - id: build-verify
+      - id: docs-build-verify
         name: Build and verify
-        uses: ./.github/actions/docs-pr
+        uses: ./.github/actions/docs/docs-build-verify
         with:
           package-script: 'build-verify'
-          surge-deploy-url: '${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ github.event.number }}'
-          surge-deploy-id: ${{ github.event.number }}
           fail-on-warnings: true
+
+      # create deploy comment
+
+      - id: antora-component-name
+        name: Read antora component name
+        uses: jbutcher5/read-yaml@main
+        with:
+          file: './antora.yml'
+          key-path: '["name"]'
+
+      - id: antora-component-version
+        name: Read antora component version
+        uses: jbutcher5/read-yaml@main
+        with:
+          file: './antora.yml'
+          key-path: '["version"]'
+
+      - name: Comment preamble
+        run: |
+          echo "This PR contains docs changes
+          
+          You can review the changes at https://${{ needs.set-deploy-outputs.outputs.deploy-url }}
+
+          Changed files:
+          " > deploy-comment
+                  
+      - name: Add changed files to comment text
+        run: |
+          gh pr view ${{ github.event.number }} --json files --jq \
+          'limit(10; .files.[] | select(.path | contains("/pages/")) as $changes |  (.path | sub("modules/.+/pages/(?<f>.*).adoc"; "- [\(.f)](https://${{ needs.set-deploy-outputs.outputs.deploy-url }}/${{ steps.antora-component-name.outputs.data }}/${{ steps.antora-component-version.outputs.data }}/\(.f))" ) ) ) ' \
+          | npx pino-pretty >> changelog
+        env:
+          GITHUB_TOKEN: ${{ secrets.PR_COMMENT_TOKEN }}
+
+      - name: Save comment text as artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: docs
+          path: deploy-comment
 
           
       # deploy
@@ -44,7 +89,7 @@ jobs:
       # - id: deploy
       #   name: Deploy
       #   if: success() || failure()
-      #   uses: ./.github/actions/deploy
+      #   uses: ./.github/actions/docs/deploy
       #   with:
       #     surge-token: ${{ secrets.SURGE_TOKEN }}
       #     surge-deploy-url: ${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ github.event.number }}.surge.sh
@@ -59,20 +104,20 @@ jobs:
 
       # lint tests - new links
 
-      - id: lint
-        name: Lint
-        if: success() || failure()
-        uses: ./.github/actions/lint/links
-        with:
-          git-token: ${{ secrets.PR_COMMENT_TOKEN }}
-          surge-deploy-url: '${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ github.event.number }}'
-          base: ${{ github.base_ref }}
-          head: ${{ github.head_ref }}
+      # - id: lint
+      #   name: Lint
+      #   if: success() || failure()
+      #   uses: ./.github/actions/docs/lint/links
+      #   with:
+      #     git-token: ${{ secrets.PR_COMMENT_TOKEN }}
+      #     surge-deploy-url: '${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ github.event.number }}'
+      #     base: ${{ github.base_ref }}
+      #     head: ${{ github.head_ref }}
 
       # - id: vale
       #   name: Vale
       #   if: success() || failure()
-      #   uses: ./.github/actions/lint/vale
+      #   uses: ./.github/actions/docs/lint/vale
       #   with:
       #     git-token: ${{ secrets.PR_COMMENT_TOKEN }}
       #     surge-deploy-url: '${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ github.event.number }}'
@@ -87,7 +132,7 @@ jobs:
 
 
 
-        # uses: ./.github/actions/deploy
+        # uses: ./.github/actions/docs/deploy
         # with:
         #   surge-tokem: ${{ secrets.SURGE_TOKEN }}
         #   surge-deploy-url: ${{ github.event.repository.owner.login}}-${{ github.event.repository.name}}-${{ github.event.number }}.surge.sh
