200

diff --git a/.github/workflows/docs-pr-links.yml b/.github/workflows/docs-pr-links.yml
--- a/.github/workflows/docs-pr-links.yml
+++ b/.github/workflows/docs-pr-links.yml
@@ -84,20 +84,20 @@ jobs:
           fi
           
       - id: error-count
-        name: 404 count
+        name: 404 error count
         run: |
           errorcount=$(grep '(HTTP 404)' -c link-log.txt)
           if ! [ -z $errorcount ]; then
             echo "::error:: broken links found"
           fi
 
-      # - id: warn-count
-      #   name: 200 count
-      #   run: |
-      #     warncount=$(grep -e '(HTTP 200)' -c link-log.txt)
-      #     if ! [ -z $warncount ]; then
-      #       echo "::warning:: $warncount missing anchor links found"
-      #     fi
+      - id: warn-count
+        name: 200 warning count
+        run: |
+          warncount=$(grep -e '(HTTP 200)' -c link-log.txt)
+          if ! [ -z $warncount ]; then
+            echo "::warning:: missing anchor links found"
+          fi
 
       # - id: status
       #   name: Report status as annotations
